apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
  namespace: django-app
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "postgres123"
  SECRET_KEY: "django-insecure-local-dev-key-12345"